spring.application.name=carpooling
spring.data.mongodb.uri=${MONGO_URI_TEST}
spring.data.mongodb.database=carpooling
spring.data.mongodb.auto-index-creation=true
spring.main.allow-circular-references=true
server.port=${PORT:5001}

spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${EMAIL:}
spring.mail.password=${PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB


spring.data.redis.url=${REDIS_URI}
spring.cache.type=redis

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}


spring.rabbitmq.addresses=${RABBITMQ_URI}
spring.rabbitmq.ssl.enabled=true

app.frontend-url=${FRONTEND_URL:https://carpooling-frontend-iota.vercel.app}
app.backend-url=${BACKEND_URL:https://carpooling-5as1.onrender.com}
app.google-redirect-uri=${GOOGLE_REDIRECT_URI:https://carpooling-5as1.onrender.com/auth/google/callback}

MAIL_PROVIDER=${MAIL_PROVIDER:sendgrid}
MAIL_FROM_EMAIL=${MAIL_FROM_EMAIL:${EMAIL:}}
SENDGRID_API_KEY=${SENDGRID_API_KEY:}

